from pywilliwaw.fan import TemperatureSensor, Williwaw, discover, find_by_address, find_by_name
from pywilliwaw.protocol import (
    COMMAND_CHAR,
    FANCONTROL_CHAR,
    FANSTATE_CHAR,
    SENSORS_CHAR,
    SENSORLIST_CHAR,
    DEVICENAME_CHAR,
    OSCILLATION_SPEED_HIGH,
    OSCILLATION_SPEED_LOW,
    OSCILLATION_SPEED_MEDIUM,
    SLEEP_MAX_MIN,
    SPEED_MAX,
    SPEED_MIN,
    make_fan_toggle_cmd,
    make_sweep_toggle_cmd,
    make_center_cmd,
    make_calibrate_sensors_cmd,
    make_speed_cmd,
    make_wake_timer_cmd,
    status_with_speed,
    status_with_sweep,
    status_with_oscillation_speed,
    status_with_thermostat,
    status_with_temp_diff,
    status_clear_auto_mode,
    status_with_scheduled_stop,
)

__all__ = [
    "Williwaw",
    "TemperatureSensor",
    "discover",
    "find_by_address",
    "find_by_name",
    # characteristics
    "COMMAND_CHAR",
    "FANCONTROL_CHAR",
    "FANSTATE_CHAR",
    "SENSORS_CHAR",
    "SENSORLIST_CHAR",
    "DEVICENAME_CHAR",
    # limits
    "SPEED_MIN",
    "SPEED_MAX",
    "SLEEP_MAX_MIN",
    "OSCILLATION_SPEED_LOW",
    "OSCILLATION_SPEED_MEDIUM",
    "OSCILLATION_SPEED_HIGH",
    # packet builders
    "make_fan_toggle_cmd",
    "make_sweep_toggle_cmd",
    "make_center_cmd",
    "make_calibrate_sensors_cmd",
    "make_speed_cmd",
    "make_wake_timer_cmd",
    "status_with_speed",
    "status_with_sweep",
    "status_with_oscillation_speed",
    "status_with_thermostat",
    "status_with_temp_diff",
    "status_clear_auto_mode",
    "status_with_scheduled_stop",
]
